include("Model.jl")

using Flux, Serialization, WAV, Zygote, Distributions
 
# Both autoencoders have constraints on encoder & decoder output shapes
# encoders output array (model_size, 1, out_channels, :)
# decoders output array (H, W, in_channels, :) where H & W are the size of the input data
# So essentially, we can run both of them on the same training & loss functions 


function create_audio_autoencoder( model_size=128, sample_size=1764 )

    encoder = Chain(
    
        Dense(sample_size, model_size),
        Dense(model_size, model_size, celu),
    
        Dropout(0.5)
    )
    
    decoder = Chain(

        Dense(model_size, model_size, celu),
        Dense(model_size, sample_size)
            
    )
    
    std          = Dense( model_size, model_size, celu )
    mean         = Dense( model_size, model_size, celu )

    return encoder, decoder, mean, std

end    


function create_video_autoencoder( model_size=128, sample_size=640 )

    encoder_shape::Integer = ceil(sqrt(model_size))

    encoder = Chain(
    
        Conv( (3, 3), (3 => 4),  pad=2, stride=1), 
        Conv( (3, 3), (4 => 8),  pad=2, stride=2), 
        Conv( (3, 3), (8 => 16), pad=2, stride=2),



        AdaptiveMeanPool( ( encoder_shape, encoder_shape ) ),

        x -> reshape(x, ( encoder_shape * encoder_shape, 1, size(x)[3], : ) ),

        Dropout( 0.5 )

    )
    
    decoder = Chain(

        AdaptiveMeanPool( ( (encoder_shape - 1) * (encoder_shape - 1), 1) ),

        x -> reshape(x, ((encoder_shape - 1), (encoder_shape - 1), size(x)[3], :) ),



        ConvTranspose( (3, 3), 16 => 8, stride=2 ),
        Upsample( scale=(2, 2) ), 

        ConvTranspose( (3, 3), 8 => 4,  stride=2 ),
        Upsample( scale=(2, 2) ),

        ConvTranspose( (3, 3), 4 => 3,  stride=2 ),
        Upsample( scale=(2, 2) ), 
        
        x -> x[1:sample_size, 1:sample_size, :, :]
    
    )
    
    std          = Dense( encoder_shape * encoder_shape, model_size, celu )
    mean         = Dense( encoder_shape * encoder_shape, model_size, celu )

    return encoder, decoder, mean, std

end    



# Evaluates the output of the model given some input. 

function eval_model( encoder, decoder, mean, std, param, data )

    # Encoding process
    enc_out    = encoder( data )

    # Learns the probability distribution of the output
    means      = mean( enc_out )
    devs       = std( enc_out )

    # Samples from the distribution generated by the encoder 
    latent     = ( param .* devs ) .+ means

    # passes to decoder
    dec_out    = decoder( latent )

    return dec_out

end


# The loss function and model evaluation that should be called within the backprop/gradient scope

function loss_function( encoder, decoder, mean, std, param, x )

    y = eval_model( encoder, decoder, mean, std, param, x )
    
    return Flux.Losses.mse( y, x ), Flux.Losses.kldivergence( softmax( y ), softmax( x ) )

end

# This is the main driver for doing inference. It runs on command, i.e. almost never. 

function autoencode( num_batches )

    model, _, _ = deserialize( savename )

    encoder, decoder, mean, std = model

    out = zeros( sample_size, 1, 2, batches, num_batches )

    io  = open( data_file )

    for i in 1 : num_batches 

        data = next( io )

        unit_gaussians = ones( latent_vec_size )

        _, _, output = eval_model( encoder, decoder, mean, std, unit_gaussians, data )

        out[:, :, :, :, i] = reshape( output, size(output)[ 1:4 ] )

    end
    
    file = reshape( out, ( sample_size * num_batches * batches, 2 ) )

    file = ( file .* 2.0 ) .- 1.0

    wavwrite( file, "output.wav", Fs=22050)

    close( io )

end
