include("Model.jl")
include("InceptionVAE.jl")

using Flux, Serialization, WAV, Zygote, Distributions, CUDA
 
# Both autoencoders have constraints on encoder & decoder output shapes
# encoders output array (model_size, 1, out_channels, :)
# decoders output array (H, W, in_channels, :) where H & W are the size of the input data
# So essentially, we can run both of them on the same training & loss functions 


function create_audio_autoencoder( model_size=128, sample_size=1764 )

    encoder = Chain(
    
        Dense(sample_size, model_size, bias=false),

        Conv( (1, 1), 2 => 16, stride=1),

        Dense(model_size, model_size, celu),
    
        Dropout(0.5)
    )
    
    decoder = Chain(

        Dense(model_size, model_size, celu),

        Conv( (1, 1), 16 => 2, stride=1),

        Dense(model_size, sample_size, bias=false)
            
    )
    
    mean         = Dense( model_size, model_size, celu )
    std          = Dense( model_size, model_size, celu )

    return encoder, decoder, mean, std 

end    


function create_video_autoencoder( model_size=128, sample_size=640 )

    encoder  = inception_encoder( model_size )
    decoder  = inception_decoder( sample_size)

    mean     = Dense( model_size, model_size, celu )
    std      = Dense( model_size, model_size, celu )

    return encoder, decoder, mean, std 

end    



# Evaluates the output of the model given some input. 

function eval_model( encoder, decoder, mean, std, param, data )

    # Encoding process
    enc_out    = encoder( data )

    # Learns the probability distribution of the output
    means      = mean( enc_out )
    devs       = std( enc_out )

    # Samples from the distribution generated by the encoder 
    latent     = ( param .* devs ) .+ means

    # passes to decoder
    dec_out    = decoder( latent )

    return dec_out

end


# The loss function and model evaluation that should be called within the backprop/gradient scope

function loss_function( encoder, decoder, mean, std, param, x ) 

    y = eval_model( encoder, decoder, mean, std, param, x )
    
    return Flux.Losses.mse( y, x ), Flux.Losses.kldivergence( softmax( y ), softmax( x ) )

end
